<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>StardewModdingAPI.Mods.VirtualKeyboard</RootNamespace>
    <AssemblyName>VirtualKeyboard</AssemblyName>
    <TargetFramework>net5.0</TargetFramework>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\build\StardewValleyAndroidStuff\base_1.6.13.0\assemblies\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="StardewModdingAPI">
      <HintPath>..\SMAPI\bin\Debug\StardewModdingAPI.dll</HintPath>
    </Reference>
    <Reference Include="StardewValley">
      <HintPath>..\..\build\StardewValleyAndroidStuff\base_1.6.13.0\assemblies\StardewValley.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="manifest.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="assets\togglebutton.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SMAPI.Toolkit\SMAPI.Toolkit.csproj">
      <Project>{08184f74-60ad-4eee-a78c-f4a35ade6246}</Project>
      <Name>SMAPI.Toolkit</Name>
    </ProjectReference>
  </ItemGroup>
</Project>