#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ModLoader.Resource", IsApplication=true)]

namespace ModLoader
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000e
			public const int notification_template_icon_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_template_icon_low_bg = 2130837519;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash_logos_crop = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash_screen = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001d
			public const int action0 = 2131427357;
			
			// aapt resource value: 0x7f0b001a
			public const int action_container = 2131427354;
			
			// aapt resource value: 0x7f0b0021
			public const int action_divider = 2131427361;
			
			// aapt resource value: 0x7f0b001b
			public const int action_image = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int action_text = 2131427356;
			
			// aapt resource value: 0x7f0b002b
			public const int actions = 2131427371;
			
			// aapt resource value: 0x7f0b002f
			public const int appIcon = 2131427375;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b0014
			public const int buttonAddOrRemove = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int buttonConfig = 2131427349;
			
			// aapt resource value: 0x7f0b000d
			public const int buttonExtract = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int buttonGenerate = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int buttonLaunch = 2131427343;
			
			// aapt resource value: 0x7f0b0011
			public const int buttonSetting = 2131427345;
			
			// aapt resource value: 0x7f0b0010
			public const int buttonWiki = 2131427344;
			
			// aapt resource value: 0x7f0b001e
			public const int cancel_action = 2131427358;
			
			// aapt resource value: 0x7f0b0018
			public const int checkBoxCompat = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int checkBoxUpgrade = 2131427353;
			
			// aapt resource value: 0x7f0b0026
			public const int chronometer = 2131427366;
			
			// aapt resource value: 0x7f0b0034
			public const int description = 2131427380;
			
			// aapt resource value: 0x7f0b002d
			public const int end_padder = 2131427373;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b000b
			public const int gridLayout1 = 2131427339;
			
			// aapt resource value: 0x7f0b0028
			public const int icon = 2131427368;
			
			// aapt resource value: 0x7f0b002c
			public const int icon_group = 2131427372;
			
			// aapt resource value: 0x7f0b0027
			public const int info = 2131427367;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b000c
			public const int linearLayout1 = 2131427340;
			
			// aapt resource value: 0x7f0b0012
			public const int listView1 = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int ll_view = 2131427347;
			
			// aapt resource value: 0x7f0b0020
			public const int media_actions = 2131427360;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b002e
			public const int notificationLayout = 2131427374;
			
			// aapt resource value: 0x7f0b002a
			public const int notification_background = 2131427370;
			
			// aapt resource value: 0x7f0b0023
			public const int notification_main_column = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int notification_main_column_container = 2131427362;
			
			// aapt resource value: 0x7f0b0033
			public const int progress_bar = 2131427379;
			
			// aapt resource value: 0x7f0b0032
			public const int progress_bar_frame = 2131427378;
			
			// aapt resource value: 0x7f0b0030
			public const int progress_text = 2131427376;
			
			// aapt resource value: 0x7f0b0029
			public const int right_icon = 2131427369;
			
			// aapt resource value: 0x7f0b0024
			public const int right_side = 2131427364;
			
			// aapt resource value: 0x7f0b0035
			public const int spacer = 2131427381;
			
			// aapt resource value: 0x7f0b001f
			public const int status_bar_latest_event_content = 2131427359;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b0017
			public const int textDescription = 2131427351;
			
			// aapt resource value: 0x7f0b0016
			public const int textModName = 2131427350;
			
			// aapt resource value: 0x7f0b0025
			public const int time = 2131427365;
			
			// aapt resource value: 0x7f0b0031
			public const int time_remaining = 2131427377;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout_mod_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout_setting = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_action_tombstone = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_media_cancel_action = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_big_media_narrow_custom = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_custom_big = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_icon_group = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_lines_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_media_custom = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_chronometer = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_part_time = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int status_bar_ongoing_event_progress_bar = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int ModList = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SMDroidFiles = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080018
			public const int ApplicationName = 2131230744;
			
			// aapt resource value: 0x7f08002b
			public const int Cancel = 2131230763;
			
			// aapt resource value: 0x7f080026
			public const int CompatCheck = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int Config = 2131230761;
			
			// aapt resource value: 0x7f080024
			public const int Confirm = 2131230756;
			
			// aapt resource value: 0x7f080038
			public const int CrashReportMessage = 2131230776;
			
			// aapt resource value: 0x7f08001c
			public const int Disable = 2131230748;
			
			// aapt resource value: 0x7f08003a
			public const int Dismiss = 2131230778;
			
			// aapt resource value: 0x7f08001d
			public const int Enable = 2131230749;
			
			// aapt resource value: 0x7f080028
			public const int Error = 2131230760;
			
			// aapt resource value: 0x7f080019
			public const int Extract = 2131230745;
			
			// aapt resource value: 0x7f08002e
			public const int ExtractedMessage = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int ExtractingMessage = 2131230765;
			
			// aapt resource value: 0x7f08001a
			public const int Generate = 2131230746;
			
			// aapt resource value: 0x7f080030
			public const int GeneratedMessage = 2131230768;
			
			// aapt resource value: 0x7f08002f
			public const int GeneratingMessage = 2131230767;
			
			// aapt resource value: 0x7f080023
			public const int Ignore = 2131230755;
			
			// aapt resource value: 0x7f08001b
			public const int Launch = 2131230747;
			
			// aapt resource value: 0x7f080031
			public const int ModDownloadingMessage = 2131230769;
			
			// aapt resource value: 0x7f08001e
			public const int ModInstall = 2131230750;
			
			// aapt resource value: 0x7f080033
			public const int ModInstalledMessage = 2131230771;
			
			// aapt resource value: 0x7f08001f
			public const int ModRemove = 2131230751;
			
			// aapt resource value: 0x7f080034
			public const int ModRemovedMessage = 2131230772;
			
			// aapt resource value: 0x7f080032
			public const int NetworkErrorMessage = 2131230770;
			
			// aapt resource value: 0x7f080037
			public const int NotExtractedMessage = 2131230775;
			
			// aapt resource value: 0x7f080036
			public const int NotGeneratedMessage = 2131230774;
			
			// aapt resource value: 0x7f080035
			public const int NotInstalledMessage = 2131230773;
			
			// aapt resource value: 0x7f08002a
			public const int RemoveConfirmMessage = 2131230762;
			
			// aapt resource value: 0x7f080025
			public const int Setting = 2131230757;
			
			// aapt resource value: 0x7f08002c
			public const int StorageIsFullMessage = 2131230764;
			
			// aapt resource value: 0x7f080022
			public const int Update = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int UpdateTip = 2131230753;
			
			// aapt resource value: 0x7f080027
			public const int UpgradeCheck = 2131230759;
			
			// aapt resource value: 0x7f080039
			public const int View = 2131230777;
			
			// aapt resource value: 0x7f080020
			public const int Wiki = 2131230752;
			
			// aapt resource value: 0x7f080001
			public const int kilobytes_per_second = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int notification_download_complete = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int notification_download_failed = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int state_completed = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int state_connecting = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int state_downloading = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int state_failed = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int state_failed_cancelled = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int state_failed_fetching_url = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int state_failed_sdcard_full = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int state_failed_unlicensed = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int state_fetching_url = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int state_idle = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int state_paused_by_request = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int state_paused_network_setup_failure = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int state_paused_network_unavailable = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int state_paused_roaming = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int state_paused_sdcard_unavailable = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int state_paused_wifi_disabled = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int state_paused_wifi_unavailable = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int state_unknown = 2131230741;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			// aapt resource value: 0x7f080016
			public const int time_remaining = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int time_remaining_notification = 2131230743;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f05000f
			public const int ButtonBackground = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int NotificationText = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int NotificationTextSecondary = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int NotificationTextShadow = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int NotificationTitle = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int TextAppearance_Compat_Notification = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_Compat_Notification_Info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_Compat_Notification_Time = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TextAppearance_Compat_Notification_Title = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int Theme_Splash = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int Widget_Compat_NotificationActionContainer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_Compat_NotificationActionText = 2131034122;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
