<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\define-constant.targets" />
  <PropertyGroup>
    <AssemblyName>ConsoleCommands</AssemblyName>
    <RootNamespace>StardewModdingAPI.Mods.ConsoleCommands</RootNamespace>
    <TargetFramework>net5.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <Import Project="..\..\build\common.targets" />

  <ItemGroup Condition="'$(BUILD_FOR_MOBILE)' == ''">
    <ProjectReference Include="..\SMAPI\SMAPI.csproj" Private="False" />
  </ItemGroup>

  <ItemGroup Condition="'$(BUILD_FOR_MOBILE)' == ''">
    <Reference Include="MonoGame.Framework" HintPath="$(GamePath)\MonoGame.Framework.dll" Private="False" />
    <Reference Include="Stardew Valley" HintPath="$(GamePath)\Stardew Valley.dll" Private="False" />
    <Reference Include="StardewValley.GameData" HintPath="$(GamePath)\StardewValley.GameData.dll" Private="False" />
    <Reference Include="xTile" HintPath="$(GamePath)\xTile.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="'$(BUILD_FOR_MOBILE)' != ''">
    <ProjectReference Include="..\SMAPI.Toolkit\SMAPI.Toolkit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(BUILD_FOR_MOBILE)' != ''">
    <Reference Include="MonoGame.Framework">
      <HintPath>..\..\..\Downloads\StardewValleyAndroidStuff\base_1.4.5.145\assemblies\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="StardewModdingAPI">
      <HintPath>..\SMAPI\bin\Release\StardewModdingAPI.dll</HintPath>
    </Reference>
    <Reference Include="StardewValley">
      <HintPath>..\..\..\Downloads\StardewValleyAndroidStuff\base_1.4.5.151\assemblies_decrypt\StardewValley.dll</HintPath>
    </Reference>
    <Reference Include="StardewValley.GameData">
      <HintPath>..\..\..\Downloads\StardewValleyAndroidStuff\base_1.4.5.151\assemblies_decrypt\StardewValley.GameData.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Import Project="..\SMAPI.Internal\SMAPI.Internal.projitems" Label="Shared" />
</Project>
