#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Loader.Resource", IsApplication=true)]

namespace Loader
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::StardewModdingAPI.Resource.Attribute.alpha = global::Loader.Resource.Attribute.alpha;
			global::StardewModdingAPI.Resource.Attribute.font = global::Loader.Resource.Attribute.font;
			global::StardewModdingAPI.Resource.Attribute.fontProviderAuthority = global::Loader.Resource.Attribute.fontProviderAuthority;
			global::StardewModdingAPI.Resource.Attribute.fontProviderCerts = global::Loader.Resource.Attribute.fontProviderCerts;
			global::StardewModdingAPI.Resource.Attribute.fontProviderFetchStrategy = global::Loader.Resource.Attribute.fontProviderFetchStrategy;
			global::StardewModdingAPI.Resource.Attribute.fontProviderFetchTimeout = global::Loader.Resource.Attribute.fontProviderFetchTimeout;
			global::StardewModdingAPI.Resource.Attribute.fontProviderPackage = global::Loader.Resource.Attribute.fontProviderPackage;
			global::StardewModdingAPI.Resource.Attribute.fontProviderQuery = global::Loader.Resource.Attribute.fontProviderQuery;
			global::StardewModdingAPI.Resource.Attribute.fontStyle = global::Loader.Resource.Attribute.fontStyle;
			global::StardewModdingAPI.Resource.Attribute.fontVariationSettings = global::Loader.Resource.Attribute.fontVariationSettings;
			global::StardewModdingAPI.Resource.Attribute.fontWeight = global::Loader.Resource.Attribute.fontWeight;
			global::StardewModdingAPI.Resource.Attribute.ttcIndex = global::Loader.Resource.Attribute.ttcIndex;
			global::StardewModdingAPI.Resource.Color.notification_action_color_filter = global::Loader.Resource.Color.notification_action_color_filter;
			global::StardewModdingAPI.Resource.Color.notification_icon_bg_color = global::Loader.Resource.Color.notification_icon_bg_color;
			global::StardewModdingAPI.Resource.Color.ripple_material_light = global::Loader.Resource.Color.ripple_material_light;
			global::StardewModdingAPI.Resource.Color.secondary_text_default_material_light = global::Loader.Resource.Color.secondary_text_default_material_light;
			global::StardewModdingAPI.Resource.Dimension.compat_button_inset_horizontal_material = global::Loader.Resource.Dimension.compat_button_inset_horizontal_material;
			global::StardewModdingAPI.Resource.Dimension.compat_button_inset_vertical_material = global::Loader.Resource.Dimension.compat_button_inset_vertical_material;
			global::StardewModdingAPI.Resource.Dimension.compat_button_padding_horizontal_material = global::Loader.Resource.Dimension.compat_button_padding_horizontal_material;
			global::StardewModdingAPI.Resource.Dimension.compat_button_padding_vertical_material = global::Loader.Resource.Dimension.compat_button_padding_vertical_material;
			global::StardewModdingAPI.Resource.Dimension.compat_control_corner_material = global::Loader.Resource.Dimension.compat_control_corner_material;
			global::StardewModdingAPI.Resource.Dimension.compat_notification_large_icon_max_height = global::Loader.Resource.Dimension.compat_notification_large_icon_max_height;
			global::StardewModdingAPI.Resource.Dimension.compat_notification_large_icon_max_width = global::Loader.Resource.Dimension.compat_notification_large_icon_max_width;
			global::StardewModdingAPI.Resource.Dimension.notification_action_icon_size = global::Loader.Resource.Dimension.notification_action_icon_size;
			global::StardewModdingAPI.Resource.Dimension.notification_action_text_size = global::Loader.Resource.Dimension.notification_action_text_size;
			global::StardewModdingAPI.Resource.Dimension.notification_big_circle_margin = global::Loader.Resource.Dimension.notification_big_circle_margin;
			global::StardewModdingAPI.Resource.Dimension.notification_content_margin_start = global::Loader.Resource.Dimension.notification_content_margin_start;
			global::StardewModdingAPI.Resource.Dimension.notification_large_icon_height = global::Loader.Resource.Dimension.notification_large_icon_height;
			global::StardewModdingAPI.Resource.Dimension.notification_large_icon_width = global::Loader.Resource.Dimension.notification_large_icon_width;
			global::StardewModdingAPI.Resource.Dimension.notification_main_column_padding_top = global::Loader.Resource.Dimension.notification_main_column_padding_top;
			global::StardewModdingAPI.Resource.Dimension.notification_media_narrow_margin = global::Loader.Resource.Dimension.notification_media_narrow_margin;
			global::StardewModdingAPI.Resource.Dimension.notification_right_icon_size = global::Loader.Resource.Dimension.notification_right_icon_size;
			global::StardewModdingAPI.Resource.Dimension.notification_right_side_padding_top = global::Loader.Resource.Dimension.notification_right_side_padding_top;
			global::StardewModdingAPI.Resource.Dimension.notification_small_icon_background_padding = global::Loader.Resource.Dimension.notification_small_icon_background_padding;
			global::StardewModdingAPI.Resource.Dimension.notification_small_icon_size_as_large = global::Loader.Resource.Dimension.notification_small_icon_size_as_large;
			global::StardewModdingAPI.Resource.Dimension.notification_subtext_size = global::Loader.Resource.Dimension.notification_subtext_size;
			global::StardewModdingAPI.Resource.Dimension.notification_top_pad = global::Loader.Resource.Dimension.notification_top_pad;
			global::StardewModdingAPI.Resource.Dimension.notification_top_pad_large_text = global::Loader.Resource.Dimension.notification_top_pad_large_text;
			global::StardewModdingAPI.Resource.Drawable.notification_action_background = global::Loader.Resource.Drawable.notification_action_background;
			global::StardewModdingAPI.Resource.Drawable.notification_bg = global::Loader.Resource.Drawable.notification_bg;
			global::StardewModdingAPI.Resource.Drawable.notification_bg_low = global::Loader.Resource.Drawable.notification_bg_low;
			global::StardewModdingAPI.Resource.Drawable.notification_bg_low_normal = global::Loader.Resource.Drawable.notification_bg_low_normal;
			global::StardewModdingAPI.Resource.Drawable.notification_bg_low_pressed = global::Loader.Resource.Drawable.notification_bg_low_pressed;
			global::StardewModdingAPI.Resource.Drawable.notification_bg_normal = global::Loader.Resource.Drawable.notification_bg_normal;
			global::StardewModdingAPI.Resource.Drawable.notification_bg_normal_pressed = global::Loader.Resource.Drawable.notification_bg_normal_pressed;
			global::StardewModdingAPI.Resource.Drawable.notification_icon_background = global::Loader.Resource.Drawable.notification_icon_background;
			global::StardewModdingAPI.Resource.Drawable.notification_template_icon_bg = global::Loader.Resource.Drawable.notification_template_icon_bg;
			global::StardewModdingAPI.Resource.Drawable.notification_template_icon_low_bg = global::Loader.Resource.Drawable.notification_template_icon_low_bg;
			global::StardewModdingAPI.Resource.Drawable.notification_tile_bg = global::Loader.Resource.Drawable.notification_tile_bg;
			global::StardewModdingAPI.Resource.Drawable.notify_panel_notification_icon_bg = global::Loader.Resource.Drawable.notify_panel_notification_icon_bg;
			global::StardewModdingAPI.Resource.Id.actions = global::Loader.Resource.Id.actions;
			global::StardewModdingAPI.Resource.Id.action_container = global::Loader.Resource.Id.action_container;
			global::StardewModdingAPI.Resource.Id.action_divider = global::Loader.Resource.Id.action_divider;
			global::StardewModdingAPI.Resource.Id.action_image = global::Loader.Resource.Id.action_image;
			global::StardewModdingAPI.Resource.Id.action_text = global::Loader.Resource.Id.action_text;
			global::StardewModdingAPI.Resource.Id.appIcon = global::Loader.Resource.Id.appIcon;
			global::StardewModdingAPI.Resource.Id.async = global::Loader.Resource.Id.async;
			global::StardewModdingAPI.Resource.Id.blocking = global::Loader.Resource.Id.blocking;
			global::StardewModdingAPI.Resource.Id.chronometer = global::Loader.Resource.Id.chronometer;
			global::StardewModdingAPI.Resource.Id.description = global::Loader.Resource.Id.description;
			global::StardewModdingAPI.Resource.Id.forever = global::Loader.Resource.Id.forever;
			global::StardewModdingAPI.Resource.Id.icon = global::Loader.Resource.Id.icon;
			global::StardewModdingAPI.Resource.Id.icon_group = global::Loader.Resource.Id.icon_group;
			global::StardewModdingAPI.Resource.Id.info = global::Loader.Resource.Id.info;
			global::StardewModdingAPI.Resource.Id.italic = global::Loader.Resource.Id.italic;
			global::StardewModdingAPI.Resource.Id.line1 = global::Loader.Resource.Id.line1;
			global::StardewModdingAPI.Resource.Id.line3 = global::Loader.Resource.Id.line3;
			global::StardewModdingAPI.Resource.Id.normal = global::Loader.Resource.Id.normal;
			global::StardewModdingAPI.Resource.Id.notificationLayout = global::Loader.Resource.Id.notificationLayout;
			global::StardewModdingAPI.Resource.Id.notification_background = global::Loader.Resource.Id.notification_background;
			global::StardewModdingAPI.Resource.Id.notification_main_column = global::Loader.Resource.Id.notification_main_column;
			global::StardewModdingAPI.Resource.Id.notification_main_column_container = global::Loader.Resource.Id.notification_main_column_container;
			global::StardewModdingAPI.Resource.Id.progress_bar = global::Loader.Resource.Id.progress_bar;
			global::StardewModdingAPI.Resource.Id.progress_bar_frame = global::Loader.Resource.Id.progress_bar_frame;
			global::StardewModdingAPI.Resource.Id.progress_text = global::Loader.Resource.Id.progress_text;
			global::StardewModdingAPI.Resource.Id.right_icon = global::Loader.Resource.Id.right_icon;
			global::StardewModdingAPI.Resource.Id.right_side = global::Loader.Resource.Id.right_side;
			global::StardewModdingAPI.Resource.Id.spacer = global::Loader.Resource.Id.spacer;
			global::StardewModdingAPI.Resource.Id.tag_transition_group = global::Loader.Resource.Id.tag_transition_group;
			global::StardewModdingAPI.Resource.Id.tag_unhandled_key_event_manager = global::Loader.Resource.Id.tag_unhandled_key_event_manager;
			global::StardewModdingAPI.Resource.Id.tag_unhandled_key_listeners = global::Loader.Resource.Id.tag_unhandled_key_listeners;
			global::StardewModdingAPI.Resource.Id.text = global::Loader.Resource.Id.text;
			global::StardewModdingAPI.Resource.Id.text2 = global::Loader.Resource.Id.text2;
			global::StardewModdingAPI.Resource.Id.time = global::Loader.Resource.Id.time;
			global::StardewModdingAPI.Resource.Id.time_remaining = global::Loader.Resource.Id.time_remaining;
			global::StardewModdingAPI.Resource.Id.title = global::Loader.Resource.Id.title;
			global::StardewModdingAPI.Resource.Integer.status_bar_notification_info_maxnum = global::Loader.Resource.Integer.status_bar_notification_info_maxnum;
			global::StardewModdingAPI.Resource.Layout.notification_action = global::Loader.Resource.Layout.notification_action;
			global::StardewModdingAPI.Resource.Layout.notification_action_tombstone = global::Loader.Resource.Layout.notification_action_tombstone;
			global::StardewModdingAPI.Resource.Layout.notification_template_custom_big = global::Loader.Resource.Layout.notification_template_custom_big;
			global::StardewModdingAPI.Resource.Layout.notification_template_icon_group = global::Loader.Resource.Layout.notification_template_icon_group;
			global::StardewModdingAPI.Resource.Layout.notification_template_part_chronometer = global::Loader.Resource.Layout.notification_template_part_chronometer;
			global::StardewModdingAPI.Resource.Layout.notification_template_part_time = global::Loader.Resource.Layout.notification_template_part_time;
			global::StardewModdingAPI.Resource.Layout.status_bar_ongoing_event_progress_bar = global::Loader.Resource.Layout.status_bar_ongoing_event_progress_bar;
			global::StardewModdingAPI.Resource.String.app_name = global::Loader.Resource.String.app_name;
			global::StardewModdingAPI.Resource.String.hello = global::Loader.Resource.String.hello;
			global::StardewModdingAPI.Resource.String.kilobytes_per_second = global::Loader.Resource.String.kilobytes_per_second;
			global::StardewModdingAPI.Resource.String.notification_download_complete = global::Loader.Resource.String.notification_download_complete;
			global::StardewModdingAPI.Resource.String.notification_download_failed = global::Loader.Resource.String.notification_download_failed;
			global::StardewModdingAPI.Resource.String.state_completed = global::Loader.Resource.String.state_completed;
			global::StardewModdingAPI.Resource.String.state_connecting = global::Loader.Resource.String.state_connecting;
			global::StardewModdingAPI.Resource.String.state_downloading = global::Loader.Resource.String.state_downloading;
			global::StardewModdingAPI.Resource.String.state_failed = global::Loader.Resource.String.state_failed;
			global::StardewModdingAPI.Resource.String.state_failed_cancelled = global::Loader.Resource.String.state_failed_cancelled;
			global::StardewModdingAPI.Resource.String.state_failed_fetching_url = global::Loader.Resource.String.state_failed_fetching_url;
			global::StardewModdingAPI.Resource.String.state_failed_sdcard_full = global::Loader.Resource.String.state_failed_sdcard_full;
			global::StardewModdingAPI.Resource.String.state_failed_unlicensed = global::Loader.Resource.String.state_failed_unlicensed;
			global::StardewModdingAPI.Resource.String.state_fetching_url = global::Loader.Resource.String.state_fetching_url;
			global::StardewModdingAPI.Resource.String.state_idle = global::Loader.Resource.String.state_idle;
			global::StardewModdingAPI.Resource.String.state_paused_by_request = global::Loader.Resource.String.state_paused_by_request;
			global::StardewModdingAPI.Resource.String.state_paused_network_setup_failure = global::Loader.Resource.String.state_paused_network_setup_failure;
			global::StardewModdingAPI.Resource.String.state_paused_network_unavailable = global::Loader.Resource.String.state_paused_network_unavailable;
			global::StardewModdingAPI.Resource.String.state_paused_roaming = global::Loader.Resource.String.state_paused_roaming;
			global::StardewModdingAPI.Resource.String.state_paused_sdcard_unavailable = global::Loader.Resource.String.state_paused_sdcard_unavailable;
			global::StardewModdingAPI.Resource.String.state_paused_wifi_disabled = global::Loader.Resource.String.state_paused_wifi_disabled;
			global::StardewModdingAPI.Resource.String.state_paused_wifi_unavailable = global::Loader.Resource.String.state_paused_wifi_unavailable;
			global::StardewModdingAPI.Resource.String.state_unknown = global::Loader.Resource.String.state_unknown;
			global::StardewModdingAPI.Resource.String.status_bar_notification_info_overflow = global::Loader.Resource.String.status_bar_notification_info_overflow;
			global::StardewModdingAPI.Resource.String.time_remaining = global::Loader.Resource.String.time_remaining;
			global::StardewModdingAPI.Resource.String.time_remaining_notification = global::Loader.Resource.String.time_remaining_notification;
			global::StardewModdingAPI.Resource.Style.ButtonBackground = global::Loader.Resource.Style.ButtonBackground;
			global::StardewModdingAPI.Resource.Style.NotificationText = global::Loader.Resource.Style.NotificationText;
			global::StardewModdingAPI.Resource.Style.NotificationTextSecondary = global::Loader.Resource.Style.NotificationTextSecondary;
			global::StardewModdingAPI.Resource.Style.NotificationTextShadow = global::Loader.Resource.Style.NotificationTextShadow;
			global::StardewModdingAPI.Resource.Style.NotificationTitle = global::Loader.Resource.Style.NotificationTitle;
			global::StardewModdingAPI.Resource.Style.TextAppearance_Compat_Notification = global::Loader.Resource.Style.TextAppearance_Compat_Notification;
			global::StardewModdingAPI.Resource.Style.TextAppearance_Compat_Notification_Info = global::Loader.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::StardewModdingAPI.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Loader.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::StardewModdingAPI.Resource.Style.TextAppearance_Compat_Notification_Time = global::Loader.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::StardewModdingAPI.Resource.Style.TextAppearance_Compat_Notification_Title = global::Loader.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::StardewModdingAPI.Resource.Style.Widget_Compat_NotificationActionContainer = global::Loader.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::StardewModdingAPI.Resource.Style.Widget_Compat_NotificationActionText = global::Loader.Resource.Style.Widget_Compat_NotificationActionText;
			global::StardewModdingAPI.Resource.Styleable.ColorStateListItem = global::Loader.Resource.Styleable.ColorStateListItem;
			global::StardewModdingAPI.Resource.Styleable.ColorStateListItem_alpha = global::Loader.Resource.Styleable.ColorStateListItem_alpha;
			global::StardewModdingAPI.Resource.Styleable.ColorStateListItem_android_alpha = global::Loader.Resource.Styleable.ColorStateListItem_android_alpha;
			global::StardewModdingAPI.Resource.Styleable.ColorStateListItem_android_color = global::Loader.Resource.Styleable.ColorStateListItem_android_color;
			global::StardewModdingAPI.Resource.Styleable.FontFamily = global::Loader.Resource.Styleable.FontFamily;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont = global::Loader.Resource.Styleable.FontFamilyFont;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_android_font = global::Loader.Resource.Styleable.FontFamilyFont_android_font;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_android_fontStyle = global::Loader.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::Loader.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_android_fontWeight = global::Loader.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::Loader.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_font = global::Loader.Resource.Styleable.FontFamilyFont_font;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_fontStyle = global::Loader.Resource.Styleable.FontFamilyFont_fontStyle;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::Loader.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_fontWeight = global::Loader.Resource.Styleable.FontFamilyFont_fontWeight;
			global::StardewModdingAPI.Resource.Styleable.FontFamilyFont_ttcIndex = global::Loader.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderAuthority = global::Loader.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderCerts = global::Loader.Resource.Styleable.FontFamily_fontProviderCerts;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Loader.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Loader.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderPackage = global::Loader.Resource.Styleable.FontFamily_fontProviderPackage;
			global::StardewModdingAPI.Resource.Styleable.FontFamily_fontProviderQuery = global::Loader.Resource.Styleable.FontFamily_fontProviderQuery;
			global::StardewModdingAPI.Resource.Styleable.GradientColor = global::Loader.Resource.Styleable.GradientColor;
			global::StardewModdingAPI.Resource.Styleable.GradientColorItem = global::Loader.Resource.Styleable.GradientColorItem;
			global::StardewModdingAPI.Resource.Styleable.GradientColorItem_android_color = global::Loader.Resource.Styleable.GradientColorItem_android_color;
			global::StardewModdingAPI.Resource.Styleable.GradientColorItem_android_offset = global::Loader.Resource.Styleable.GradientColorItem_android_offset;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_centerColor = global::Loader.Resource.Styleable.GradientColor_android_centerColor;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_centerX = global::Loader.Resource.Styleable.GradientColor_android_centerX;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_centerY = global::Loader.Resource.Styleable.GradientColor_android_centerY;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_endColor = global::Loader.Resource.Styleable.GradientColor_android_endColor;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_endX = global::Loader.Resource.Styleable.GradientColor_android_endX;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_endY = global::Loader.Resource.Styleable.GradientColor_android_endY;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_gradientRadius = global::Loader.Resource.Styleable.GradientColor_android_gradientRadius;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_startColor = global::Loader.Resource.Styleable.GradientColor_android_startColor;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_startX = global::Loader.Resource.Styleable.GradientColor_android_startX;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_startY = global::Loader.Resource.Styleable.GradientColor_android_startY;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_tileMode = global::Loader.Resource.Styleable.GradientColor_android_tileMode;
			global::StardewModdingAPI.Resource.Styleable.GradientColor_android_type = global::Loader.Resource.Styleable.GradientColor_android_type;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7f010008
			public const int font = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderCerts = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchStrategy = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderFetchTimeout = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderPackage = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderQuery = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int fontStyle = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int fontWeight = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int ttcIndex = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080006
			public const int colorAccent = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int colorPrimary = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int colorPrimaryDark = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int ic_launcher_background = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int compat_notification_large_icon_max_height = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int compat_notification_large_icon_max_width = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_action_icon_size = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int notification_action_text_size = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_big_circle_margin = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int notification_large_icon_height = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int notification_large_icon_width = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int notification_right_icon_size = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int notification_small_icon_background_padding = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_small_icon_size_as_large = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_subtext_size = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int notification_top_pad = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int notification_top_pad_large_text = 2131165205;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000e
			public const int notification_template_icon_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_template_icon_low_bg = 2130837519;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash_logos_crop = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash_screen = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000d
			public const int action_container = 2131361805;
			
			// aapt resource value: 0x7f0a0019
			public const int action_divider = 2131361817;
			
			// aapt resource value: 0x7f0a000e
			public const int action_image = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int action_text = 2131361807;
			
			// aapt resource value: 0x7f0a001a
			public const int actions = 2131361818;
			
			// aapt resource value: 0x7f0a001d
			public const int appIcon = 2131361821;
			
			// aapt resource value: 0x7f0a0008
			public const int async = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int blocking = 2131361801;
			
			// aapt resource value: 0x7f0a0018
			public const int chronometer = 2131361816;
			
			// aapt resource value: 0x7f0a0022
			public const int description = 2131361826;
			
			// aapt resource value: 0x7f0a000a
			public const int forever = 2131361802;
			
			// aapt resource value: 0x7f0a0011
			public const int icon = 2131361809;
			
			// aapt resource value: 0x7f0a001b
			public const int icon_group = 2131361819;
			
			// aapt resource value: 0x7f0a0014
			public const int info = 2131361812;
			
			// aapt resource value: 0x7f0a000b
			public const int italic = 2131361803;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int normal = 2131361804;
			
			// aapt resource value: 0x7f0a001c
			public const int notificationLayout = 2131361820;
			
			// aapt resource value: 0x7f0a0016
			public const int notification_background = 2131361814;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_main_column = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_main_column_container = 2131361808;
			
			// aapt resource value: 0x7f0a0021
			public const int progress_bar = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int progress_bar_frame = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int progress_text = 2131361822;
			
			// aapt resource value: 0x7f0a0015
			public const int right_icon = 2131361813;
			
			// aapt resource value: 0x7f0a0013
			public const int right_side = 2131361811;
			
			// aapt resource value: 0x7f0a0023
			public const int spacer = 2131361827;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int tag_unhandled_key_event_manager = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int tag_unhandled_key_listeners = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int text = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int text2 = 2131361798;
			
			// aapt resource value: 0x7f0a0017
			public const int time = 2131361815;
			
			// aapt resource value: 0x7f0a001f
			public const int time_remaining = 2131361823;
			
			// aapt resource value: 0x7f0a0007
			public const int title = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int notification_action = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action_tombstone = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_template_custom_big = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_icon_group = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_part_chronometer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_time = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int status_bar_ongoing_event_progress_bar = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_background = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_foreground = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_launcher_round = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001a
			public const int action_settings = 2131099674;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int kilobytes_per_second = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_download_complete = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int notification_download_failed = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int state_completed = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int state_connecting = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int state_downloading = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int state_failed = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int state_failed_cancelled = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int state_failed_fetching_url = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int state_failed_sdcard_full = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int state_failed_unlicensed = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int state_fetching_url = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int state_idle = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int state_paused_by_request = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int state_paused_network_setup_failure = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int state_paused_network_unavailable = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int state_paused_roaming = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int state_paused_sdcard_unavailable = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int state_paused_wifi_disabled = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int state_paused_wifi_unavailable = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int state_unknown = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int time_remaining = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int time_remaining_notification = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f09000a
			public const int ButtonBackground = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int NotificationText = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int NotificationTextSecondary = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int NotificationTextShadow = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int NotificationTitle = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int Theme_Splash = 2131296268;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int provider_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
