<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>StardewModdingAPI</RootNamespace>
    <Description>Provides toolkit interfaces which are available to SMAPI mods.</Description>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\..\build\mobile-common.targets" />
</Project>
